export enum ErrorType {
  TYPES_EMPTY = 'TYPES_EMPTY',
  AIRPORTS_EMPTY = 'AIRPORTS_EMPTY',
  AIRPORTS_PATTERN = 'AIRPORTS_PATTERN',
  COUNTRIES_EMPTY = 'COUNTRIES_EMPTY',
  COUNTRIES_PATTERN = 'COUNTRIES_PATTERN',
}
