export enum ErrorType {
  TYPES_EMPTY = 'TYPES_EMPTY',
  AIRPORTS_COUNTRIES_EMPTY = 'AIRPORTS_COUNTRIES_EMPTY',
  AIRPORTS_PATTERN = 'AIRPORTS_PATTERN',
  COUNTRIES_PATTERN = 'COUNTRIES_PATTERN',
  NO_RESULTS = 'NO_RESULTS',
  COMMON = 'COMMON',
}
